language: node_js
node_js:
- '8'
after_success:
- bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - node_modules
before_deploy: npm run build
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: d8mPPaNtukes9i20tThZqUG9TV8VoIpZx76g6F6WxHav5V0ppZbCGVnVX54QNHEbeATIVWLFmM3CfkcIG3uRMNLEvz9yDg8RU4f+B3drgGBKIt1SUzQlmRVA8hqFx9ciwmnJhtojG/wYn24+OlHMwaFoJ3ci1L3w0zi5IVqwS5Phg9EOP4Y6+ATyMoEHrxDHqH9PN4h+5tFQ0LzqnvkdtxDyWgnr4gJT0x3vCKPxJrYtW9/KTnH2RDpEAZAIcR1Pq92qajJnrfozFujqPaZTMrOMs0Xi4+sQOY1l3WZdG19tNVKlx4Px8zCSWaI/AVarF8Rhvhq+0iIxdl0tWYwfIxVaG5SK343yn+GqnLt35LLbXv1y50RteQ56+MYLm6QbmU8lqECZR5wP7rFsuNLJiIINLqonzpF8OrDA+NkfQ0XQTecIc6V5SpsCCnJCKP//QOkYNjuRskTH8abDIgMDGOXVLSXaR60HANyXW9sfxgbBptdlBe6eZm0rlUE4FQ0NcR60VFJsorWAGrDu8n8rDO+nnVR0aZF5kE5Tkczv3oz/SJ0bmb4HGe0zvEQj2p3admKeg297i+S8G27hZGbDUmdmKyAMrY6IX/ARvyjkv8ig7QLpl4XicL3WzeY0KZf91HzoRNStFpNhifb8CO3ji7P8Wk3om+Bi2vTE/3/Bt9A=
  app: oyasumi
  on:
    branch:
    - master
    - dev
    repo: MichaelQQ/Oyasumi
