language: node_js
node_js:
  - '6'
before_deploy: "npm run build"
deploy:
  provider: heroku
  api_key:
    secure: bSHt8VfVXbcE+V7H7FEEXHttFDtkj4VCsH8l+J/i1LZVD6whhv5pecUTv2wDRkAw3E6bJnxVPEPRo+z709OPR/DNNZTCX8e+f9Wl6Di+99h3jxqQfHnvM2EIN4Cj5ARALVLIEEcV4Qv18jEYfyn8ibRF5TOTONvsGaQSxXSIeL43Zd7ZlCViOvqGv1Dnm7x0MmKc1uEyuXj/V38aPCFMbJJAv3aDXqK3DTCDgKZuKCh8K1M/nWRq0RYb2B8Ll47dI8Z4n3rWkhCy1XoljlC5+VbhL7UYt6zjnzjJD21JEmywB/dC5y3+cdv0K5bFVd84TWRVA1dxD72gcemJ4zbcdBO1ej0AA/YjU7EetpWToTwrI885mGILjV0vgQvd2Fawxie7j8DCc1aKpu7L0PpjrCxsqLS1Ipi76KQbN5mj2vsMhakhi/I+BKUyFbCQqhkCrdVX7WTtxTc6s8O8nJ0AQ23d55Y/VGWJE4rtUzd+gBz6JD4vskXRMtu7WKeJwp7Akn6t0kFnQfSl12TT1F75hH1sX/Pep6izUKcnsynnjzWANYhTOZyLUAP/CRxizNq4O5QyTonKWKDfsIg4RIImjLiQ74+mqz24sDk82DhWdTRVerSMQBdJj9IlqlLEpH1/f+KkpZjyk76TziVVKZMlgAYXYspKfhzia215EU/PxUw=
  app: oyasumi
  on:
    all_branches: true
    repo: MichaelQQ/Oyasumi
